# ansible-playbook build.yaml
---

- name: Check local requirements
  hosts: "{{ groups['build_hosts'] | default('localhost') }}"
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    build_hosts: "{{ groups['build_hosts'] | default('localhost') }}"
  tasks:
    - name: Apptainer version check
      command: apptainer --version
      register: apptainer_version_output
      changed_when: false
    - name: A supported apptainer version is installed
      assert:
        that:
          - apptainer_version_output.stdout.split(' ')[2] is version("1.3.1", ">=")
        fail_msg: "Apptainer version is not 1.3.1 or later"
    - name: containers folder check
      file:
        path: "./containers"
        state: directory

- name: Set facts for OpenFOAM forks, Ubuntu, and Open MPI versions
  hosts: "{{ groups['build_hosts'] | default('localhost') }}"
  gather_facts: no
  tasks:
    - name: Load overriden software versions
      include_vars:
        file: software_versions.yaml
      ignore_errors: yes
    - name: Set OpenFOAM forks, versions, Ubuntu, and Open MPI versions
      set_fact:
        default_openfoam_forks:
          - name: foam-extend
            versions:
              - "5.0"
            branches:
              - master
          - name: com-openfoam
            versions:
              - "2312"
          - name: org-openfoam
            versions:
              - "11"
        default_ubuntu_versions:
          - "24.04"
          - "22.04"
        default_openmpi_versions:
          - "4.1.5"
    - name: Override versions with loaded variables
      set_fact:
        openfoam_forks: "{{ openfoam_forks | default(default_openfoam_forks) }}"
        ubuntu_versions: "{{ ubuntu_versions | default(default_ubuntu_versions) }}"
        openmpi_versions: "{{ openmpi_versions | default(default_openmpi_versions) }}"
    - name: software combinations
      set_fact:
        structured_list: >-
          {{
            (structured_list | default([])) +
            (item.versions | product(item.branches | default(['default']), [item.name]))
          }}
      loop: "{{ openfoam_forks | list }}"
    - name: Build matrix
      set_fact:
        build_matrix: >-
          {{
              build_matrix | default([]) + 
              [dict({
                'version': item.0.0,
                'branch': item.0.1,
                'fork': item.0.2,
                'ubuntu': item.1,
                'openmpi': item.2
              })]
          }}
      loop: "{{ structured_list | product(ubuntu_versions, openmpi_versions) }}"
    - name: "[TEMPORARY] reject items with ubuntu 24.04 and fork org-openfoam (no Debian packages yet)"
      set_fact:
        build_matrix: >-
          {{ 
              build_matrix | selectattr('ubuntu', '!=', '24.04') +
              build_matrix | selectattr('ubuntu', '==', '24.04') | rejectattr('fork', '==', 'org-openfoam')
          }}
    - name: Display final build matrix
      debug:
        var: build_matrix

- name: OpenMPI base containers
  hosts: "{{ groups['build_hosts'] | default('localhost') }}"
  gather_facts: no
  tasks:
    - name: Check if OMPI container exist
      stat:
        path: "./containers/ubuntu-{{ item.0 }}-ompi-{{ item.1 }}.sif"
      register: ompi_container_file
      loop: "{{ ubuntu_versions | product(openmpi_versions) }}"
    - name: Build OMPI base containers if .sif file doesn't exist
      command: apptainer build
                --warn-unused-build-args
                --build-arg UBUNTU_VERSION={{ item.item.0 }}
                --build-arg OMPI_VERSION={{ item.item.1 }}
                ./containers/ubuntu-{{ item.item.0 }}-ompi-{{ item.item.1 }}.sif
                ./basic/openmpi.def
      loop: "{{ ompi_container_file.results }}"
      when: not item.stat.exists

- name: OpenFOAM base containers
  hosts: "{{ groups['build_hosts'] | default('localhost') }}"
  gather_facts: no
  tasks:
    - name: Check if base OpenFOAM containers exist
      stat:
        path: "./containers/{{ item.fork }}-{{ item.version }}-{{ item.branch }}-ubuntu-{{ item.ubuntu }}-ompi-{{ item.openmpi }}.sif"
      register: container_file
      loop: "{{ build_matrix }}"
    - name: Build base containers if corresponding .sif files don't exist
      command: apptainer build --force
                --warn-unused-build-args
                --build-arg UBUNTU_VERSION={{ item.item.ubuntu }}
                --build-arg OF_VERSION={{ item.item.version }}
                --build-arg OF_BRANCH={{ item.item.branch }}
                --build-arg OMPI_VERSION={{ item.item.openmpi }}
                ./containers/{{ item.item.fork }}-{{ item.item.version }}-{{ item.item.branch }}-ubuntu-{{ item.item.ubuntu }}-ompi-{{ item.item.openmpi }}.sif
                ./basic/{{ item.item.fork }}.def
      loop: "{{ container_file.results }}"
      when: not item.stat.exists
      ignore_errors: true # Containers install deb packages, might not available for the Ubuntu version
      run_once: true

- name: OpenFOAM projects containers
  hosts: "{{ groups['build_hosts'] | default('localhost') }}"
  gather_facts: no
  tasks:
    - name: Load overriden project versions
      include_vars:
        file: projects_versions.yaml
      ignore_errors: yes
    - name: Override project versions
      set_fact:
        projects_data: "{{  projects_data | default([]) + [lookup('vars', item.name+'-projects') | map('combine', {'fork': item.name}) ]  | flatten}}"
      loop: "{{ openfoam_forks }}"

    - name: Initialize build combinations list
      set_fact:
        combos: []
    - name: Include cartesian product tasks
      include_tasks:
        file: partials/projects_cartesian_product.yaml
      loop: "{{ projects_data }}"
      loop_control:
        loop_var: project_dict

    - name: Clean build matrix for projects
      set_fact:
        projects: "{{ combos | product(build_matrix) }}"

    - name: Display build matrix for projects
      debug:
        msg: "{{ projects }}"

    - name: Make sure container project folders are there
      command: >-
        mkdir -p containers/{{ item.0.project }}
      loop: "{{ projects }}"

    - name: Build project containers
      command: >-
          apptainer build --force
                --warn-unused-build-args {{ " " }}
                {%- set args = [] -%}
                {%- for key, value in item.0.items() -%}
                {%- if key != 'fork' and key != 'project' -%}
                {{ "--build-arg " ~ key ~ "=" ~ value }}
                {%- endif -%}
                {%- endfor -%}  {{ " " }}
                --build-arg UBUNTU_VERSION={{ item.1.ubuntu }}
                --build-arg OF_VERSION={{ item.1.version }}
                --build-arg OF_BRANCH={{ item.1.branch }}
                --build-arg OMPI_VERSION={{ item.1.openmpi }}
                containers/{{ item.0.project }}/{{ item.0.values() | join('-') }}-{{ item.1.version }}-{{ item.1.branch }}-ubuntu-{{ item.1.ubuntu }}-ompi-{{ item.1.openmpi }}.sif
                projects-{{item.0.fork}}/{{ item.0.project }}.def
      loop: "{{ projects }}"
