# ansible-playbook build.yaml --extra-vars="original_dir=$PWD" --extra-vars=@config.yaml
---

- name: Check local requirements
  hosts: "{{ groups['build_hosts'] | default('localhost') }}"
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Apptainer version check
      command: apptainer --version
      register: apptainer_version_output
      changed_when: false
    - name: A supported apptainer version is installed
      assert:
        that:
          - apptainer_version_output.stdout.split(' ')[2] is version("1.3.1", ">=")
        fail_msg: "Apptainer version is not 1.3.1 or later"
    - name: Basic containers folder check
      file:
        path: "{{ original_dir }}/containers/basic"
        state: directory
    - name: Project containers folder check
      file:
        path: "{{ original_dir }}/containers/projects"
        state: directory
    - name: Fail if original directory is not supplied
      fail:
        msg: 'The variable "original_dir" is undefined. run `ansible-playbook build.yaml --extra-vars="original_dir=$PWD @config.yaml"` instead'
      when: containers is undefined
    - name: Fail if containers config is undefined
      fail:
        msg: 'The variable "containers" is undefined. run `ansible-playbook build.yaml --extra-vars="original_dir=$PWD @config.yaml"` instead'
      when: containers is undefined
    - name: Set default pull configuration
      set_fact:
        pull: "{{ pull | default({'try_to_pull': true, 'protocol': 'oras', 'scope': 'ghcr.io/foamscience'}) }}"

- name: Base containers
  hosts: "{{ groups['build_hosts'] | default('localhost') }}"
  gather_facts: no
  tasks:
    - name: Gather MPI container information
      set_fact:
        mpi_containers: "{{ (mpi_containers | default([]) + [dict({'os': item.1.os, 'mpi': item.1.mpi})]) | unique }}"
      loop: "{{ containers.basic.items() }}"
    - name: Try to get MPI containers from registry
      shell: |
        if [ ! -f {{ original_dir }}/containers/basic/ubuntu-{{ item.os.version }}-ompi-{{ item.mpi.version }}.sif ]; then
          apptainer pull \
            {{ original_dir }}/containers/basic/ubuntu-{{ item.os.version }}-ompi-{{ item.mpi.version }}.sif \
            {{ pull.protocol }}://{{ pull.scope }}/ubuntu-{{ item.os.version }}-ompi-{{ item.mpi.version }}
        fi
      loop: "{{ mpi_containers }}"
      ignore_errors: yes
      when: pull.try_to_pull
    - name: Build OMPI base containers if .sif file doesn't exist
      shell: |
        if [ ! -f {{ original_dir }}/containers/basic/ubuntu-{{ item.os.version }}-ompi-{{ item.mpi.version }}.sif ]; then
          apptainer build \
            --warn-unused-build-args \
            --build-arg OS_VERSION={{ item.os.version }} \
            --build-arg MPI_VERSION={{ item.mpi.version }} \
            {{ original_dir }}/containers/basic/ubuntu-{{ item.os.version }}-ompi-{{ item.mpi.version }}.sif \
            {{ playbook_dir }}/basic/openmpi.def
        else
          echo "Container {{ original_dir }}/containers/basic/ubuntu-{{ item.os.version }}-ompi-{{ item.mpi.version }}.sif already exists. Skipping build."
        fi
      loop: "{{ mpi_containers }}"
    - name: Try to get base containers from registry
      shell: |
        if [ ! -f {{ original_dir }}/containers/basic/{{ item.0 }}.sif ]; then
          apptainer pull \
            {{ original_dir }}/containers/basic/{{ item.0 }}.sif \
            {{ pull.protocol }}://{{ pull.scope }}/{{ item.0 }}
        else
          echo "Container {{ original_dir }}/containers/basic/{{ item.0 }}.sif already exists. Skipping pull."
        fi
      loop: "{{ containers.basic.items() }}"
      ignore_errors: yes
      when: pull.try_to_pull
    - name: Build base containers if corresponding .sif files don't exist
      shell: |
        if [ ! -f {{ original_dir }}/containers/basic/{{ item.0 }}.sif ]; then
          apptainer build --force \
                --warn-unused-build-args \
                --build-arg OS_VERSION={{ item.1.os.version }} \
                --build-arg OPENFOAM_VERSION={{ item.1.openfoam.version }} \
                --build-arg OPENFOAM_GIT_REF={{ item.1.openfoam.branch | default('default') }} \
                --build-arg OPENMPI_VERSION={{ item.1.mpi.version }} \
                {{ original_dir }}/containers/basic/{{ item.0 }}.sif \
                {{ playbook_dir }}/basic/{{ item.1.openfoam.fork }}.def
        else
          echo "Container {{ original_dir }}/containers/basic/{{ item.0 }}.sif already exists. Skipping build."
        fi
      loop: "{{ containers.basic.items() }}"

- name: Project containers
  hosts: "{{ groups['build_hosts'] | default('localhost') }}"
  gather_facts: no
  tasks:
    - name: Initialize build combinations list
      set_fact:
        projects: []
    - name: Process projects build args
      include_tasks:
        file: "{{ playbook_dir }}/partials/projects_build_args.yaml"
      loop: "{{ containers.projects.items() }}"
      loop_control:
        loop_var: project
      when: "'projects' in containers"

    - name: Display build matrix for projects
      debug:
        var: projects
    
    - name: Build project containers
      shell: |
          apptainer build --force \
                --warn-unused-build-args {{ " " }} \
                {%- if 'build_args' in item -%} \
                {%- set args = [] -%} \
                {%- for key, value in item.build_args.items() -%} \
                {{ "--build-arg " ~ (key | upper) ~ "=" ~ value }}  {{ " " }} \
                {%- endfor -%}  {{ " " }} \
                {%- endif -%} \
                --build-arg BASE_CONTAINER={{ item.base_container }} \
                --build-arg OS_VERSION={{ containers.basic[item.base_container].os.version }} \
                --build-arg OPENMPI_VERSION={{ containers.basic[item.base_container].mpi.version }} \
                --build-arg OPENFOAM_VERSION={{ containers.basic[item.base_container].openfoam.version }} \
                --build-arg OPENFOAM_GIT_REF={{ containers.basic[item.base_container].openfoam.git_ref | default('default') }} \
                {{ original_dir }}/containers/projects/{{ item.name }}.sif \
                {{ original_dir }}/{{ item.definition }}
      loop: "{{ projects | list }}"
