# containers section defines what containers to build
containers:
  # This section builds base containers in containers/basic
  basic:
    # you get opencfd-openfoam.sif and openmpi-4.1.5-ubuntu-24.04.sif from the following entry
    opencfd-openfoam: # base container identifier
      os:
        distro: ubuntu # the only supported distro atm
        version: 24.04 # needs to be recent
      mpi:
        implementation: openmpi # the only supported MPI implementation atm
        version: 4.1.5 # recommended to match host MPI at least in major version number
      openfoam:
        fork: com-openfoam # org-openfoam, and foam-extend also supported
        version: 2312 # specific version number for the target fork
    # you get foam-extend.sif from the following entry
    #foam-extend:
    #  os:
    #    distro: ubuntu
    #    version: 24.04
    #  mpi:
    #    implementation: openmpi
    #    version: 4.1.5
    #  openfoam:
    #    fork: foam-extend
    #    version: 5.0
    #    git_ref: master # optional (default: default)
  # This section builds final containers in containers/projects
  projects:
    # you get test-master.sif and test-dev.sif from the following entry
    test:
      base_container: opencfd-openfoam # what base container to build the project against (from containers.basic above)
      definition: projects/test.def # path to container definition file (relative to CWD)
      build_args: # case-insensitive, optional build arguments for apptainer
        branch:
          - master  # will be passed as `--build-arg BRANCH=master` to `apptainer build`
          #- dev  # will be passed as `--build-arg BRANCH=master` to `apptainer build`
    # you get extend-test.sif from the following entry
    #extend-test:
    #  base_container: foam-extend
    #  definition: projects/extend-test.def

# pull section sets pull paramters
pull:
  try_to_pull: true # Do we try to pull from registry?
  protocol: "oras" # docker, or library as Pull protocol
  scope: "ghcr.io/foamscience" # so oras://ghcr.io/foamscience/<container-name>:latest is used
