name: OpenFOAM-apptainer
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Tmate debugging session'
        required: false
        default: false

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, 'docs:')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MPI, Apptainer and Ansible
        run: |
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer libopenmpi-dev python3-pip
          pip install ansible

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true

      - name: Build containers for OpenCFD's OpenFOAM
        run: |
          cp software_versions_example.yaml software_versions.yaml
          ansible-playbook build.yaml

      - name: Run test MPI application with host and container MPIs
        run: |
          mpi_out1=$(mpirun -n 2 apptainer run --sharens containers/test-com-openfoam-2312-default-ubuntu-24.04-ompi-4.1.5.sif '/opt/OMPIFoam/ompiTest')
          mpi_out2=$(apptainer run containers/test-com-openfoam-2312-default-ubuntu-24.04-ompi-4.1.5.sif 'mpirun -n 2 /opt/OMPIFoam/ompiTest')
          if [ "$mpi_out1" != "$mpi_out2" ]; then
            echo "Outputs are not identical"
            echo "Output 1: $mpi_out1"
            echo "Output 2: $mpi_out2"
            exit 1
          else
            echo "Outputs are identical"
          fi
